# NBA All-Star Weekend Challenge

Your task...answer the following questions given the dataset given about the NBA All-Star Game from the year 2000 - 2016

Become more familiar with the dataset <a href="https://www.kaggle.com/fmejia21/nba-all-star-game-20002016">here</a>

Once completed, commit this notebook to github and submit the link to the google classroom assignment.

<a href="https://classroom.google.com/u/2/c/NDc4MzEzMjI5Nzla/a/NTE3OTYxNzM2OTNa/details">Google Classroom</a>

# What is the average weight of all players who played during this time?

In [2]:
import pandas as pd
import numpy as np
allstar = pd.read_csv('./nbasheet.csv',sep=',')
allstar.head(10)
nba_weight = allstar.groupby(['Year']).mean().reset_index()
nba_weight.mean()

Year    2008.000000
WT       228.792203
dtype: float64

# What team is represented the most during this time?

In [3]:
allstar.head()
teams = allstar.groupby(['Team']).count()
teams
#Miami Heat == 28

,Year,Player,Pos,HT,WT,Selection Type,NBA Draft Status,Nationality
Team,,,,,,,,
Atlanta Hawks,18,18,18,18,18,18,18,18
Boston Celtics,26,26,26,26,26,26,26,26
Brooklyn Nets,2,2,2,2,2,2,2,2
Charlotte Bobcats,1,1,1,1,1,1,1,1
Charlotte Hornets,2,2,2,2,2,2,2,2
Chicago Bulls,12,12,12,12,12,12,12,12
Cleveland Cavaliers,17,17,17,17,17,17,17,17
Dallas Mavericks,18,18,18,18,18,18,18,18
Denver Nuggets,9,9,9,9,9,9,9,9
Detroit Pistons,15,15,15,15,15,15,15,15
Golden State Warriors,11,11,11,11,11,11,11,11
Houston Rockets,20,20,20,20,20,20,20,20
Indiana Pacers,15,15,15,15,15,15,15,15
Los Angeles Clippers,14,14,14,14,14,14,14,14
Los Angeles Lakers,25,25,25,25,25,25,25,25
Memphis Grizzlies,6,6,6,6,6,6,6,6
Miami Heat,28,28,28,28,28,28,28,28
Milwaukee Bucks,5,5,5,5,5,5,5,5
Minnesota Timberwolves,12,12,12,12,12,12,12,12
New Jersey Nets,12,12,12,12,12,12,12,12
New Orleans Hornets,9,9,9,9,9,9,9,9
New Orleans Pelicans,4,4,4,4,4,4,4,4
New York Knicks,10,10,10,10,10,10,10,10
Oklahoma City Thunder,13,13,13,13,13,13,13,13
Orlando Magic,14,14,14,14,14,14,14,14
Philadelphia Sixers,11,11,11,11,11,11,11,11
Phoenix Suns,18,18,18,18,18,18,18,18
Portland Trail Blazers,10,10,10,10,10,10,10,10
Sacramento Kings,11,11,11,11,11,11,11,11
San Antonio Spurs,25,25,25,25,25,25,25,25
Seattle SuperSonics,8,8,8,8,8,8,8,8
Toronto Raptors,16,16,16,16,16,16,16,16
Utah Jazz,9,9,9,9,9,9,9,9
Washington Wizards,13,13,13,13,13,13,13,13

# What draft class is represeted the most during this time?

In [7]:
allstar.head()
draft = allstar.groupby(['NBA Draft Status']).count().sort_values('Player')
draft.tail()
#1996 Rnd1 Pick 13

,Year,Player,Pos,HT,WT,Team,Selection Type,Nationality
NBA Draft Status,,,,,,,,
2003 Rnd 1 Pick 5,12,12,12,12,12,12,12,12
1997 Rnd 1 Pick 1,13,13,13,13,13,13,13,13
2003 Rnd 1 Pick 1,13,13,13,13,13,13,13,13
1998 Rnd 1 Pick 9,13,13,13,13,13,13,13,13
1996 Rnd 1 Pick 13,16,16,16,16,16,16,16,16

# Are foriegn players more prevalent in the All-Star Game during this time?

In [17]:
allstar.head()
us_count = allstar[allstar['Nationality'] == 'United States']
us_count.count()
not_us = allstar[allstar['Nationality'] != 'United States']
not_us.count()
# No there are more players from the US

Year                74
Player              74
Pos                 74
HT                  74
WT                  74
Team                74
Selection Type      74
NBA Draft Status    74
Nationality         74
dtype: int64

# How often are the Western All-Stars voted in by fans?

In [21]:
allstar.head(10)
vote = allstar[allstar['Selection Type'] == 'Western All-Star Fan Vote Selection']
vote.count()
# 85 players voted in by fans

Year                85
Player              85
Pos                 85
HT                  85
WT                  85
Team                85
Selection Type      85
NBA Draft Status    85
Nationality         85
dtype: int64

# How many times does Steph Curry make the All-Star game during this time period?

In [25]:
steph = allstar.groupby(['Player']).count()
allstar[allstar['Player'] == 'Stephen Curry']
# 4 times

,Year,Player,Pos,HT,WT,Team,Selection Type,NBA Draft Status,Nationality
0,2016,Stephen Curry,G,6-3,190,Golden State Warriors,Western All-Star Fan Vote Selection,2009 Rnd 1 Pick 7,United States
41,2015,Stephen Curry,G,6-3,190,Golden State Warriors,Western All-Star Fan Vote Selection,2009 Rnd 1 Pick 7,United States
63,2014,Stephen Curry,G,6-3,190,Golden State Warriors,Western All-Star Fan Vote Selection,2009 Rnd 1 Pick 7,United States
87,2013,Stephen Curry,G,6-3,190,Golden State Warriors,Western All-Star Fan Vote Selection,2009 Rnd 1 Pick 7,United States

# How many Shooting Gaurds have made the All-Star game during this time?

In [28]:
allstar[allstar['Pos'] == 'SG'].count()
# 57

Year                57
Player              57
Pos                 57
HT                  57
WT                  57
Team                57
Selection Type      57
NBA Draft Status    57
Nationality         57
dtype: int64

# How many Chicago Bulls players have made the All-Star Game during this time period?

In [29]:
teams = allstar.groupby(['Team']).count()
teams
# 12 players

,Year,Player,Pos,HT,WT,Selection Type,NBA Draft Status,Nationality
Team,,,,,,,,
Atlanta Hawks,18,18,18,18,18,18,18,18
Boston Celtics,26,26,26,26,26,26,26,26
Brooklyn Nets,2,2,2,2,2,2,2,2
Charlotte Bobcats,1,1,1,1,1,1,1,1
Charlotte Hornets,2,2,2,2,2,2,2,2
Chicago Bulls,12,12,12,12,12,12,12,12
Cleveland Cavaliers,17,17,17,17,17,17,17,17
Dallas Mavericks,18,18,18,18,18,18,18,18
Denver Nuggets,9,9,9,9,9,9,9,9
Detroit Pistons,15,15,15,15,15,15,15,15
Golden State Warriors,11,11,11,11,11,11,11,11
Houston Rockets,20,20,20,20,20,20,20,20
Indiana Pacers,15,15,15,15,15,15,15,15
Los Angeles Clippers,14,14,14,14,14,14,14,14
Los Angeles Lakers,25,25,25,25,25,25,25,25
Memphis Grizzlies,6,6,6,6,6,6,6,6
Miami Heat,28,28,28,28,28,28,28,28
Milwaukee Bucks,5,5,5,5,5,5,5,5
Minnesota Timberwolves,12,12,12,12,12,12,12,12
New Jersey Nets,12,12,12,12,12,12,12,12
New Orleans Hornets,9,9,9,9,9,9,9,9
New Orleans Pelicans,4,4,4,4,4,4,4,4
New York Knicks,10,10,10,10,10,10,10,10
Oklahoma City Thunder,13,13,13,13,13,13,13,13
Orlando Magic,14,14,14,14,14,14,14,14
Philadelphia Sixers,11,11,11,11,11,11,11,11
Phoenix Suns,18,18,18,18,18,18,18,18
Portland Trail Blazers,10,10,10,10,10,10,10,10
Sacramento Kings,11,11,11,11,11,11,11,11
San Antonio Spurs,25,25,25,25,25,25,25,25
Seattle SuperSonics,8,8,8,8,8,8,8,8
Toronto Raptors,16,16,16,16,16,16,16,16
Utah Jazz,9,9,9,9,9,9,9,9
Washington Wizards,13,13,13,13,13,13,13,13